### ISSUE TITLE
org-brain-visualize misaligned

### ISSUE THREAD

**Issue by adam52** [Kungsgeten/org-brain#15]
I am having trouble getting the pointers in `org-brain-visualize` to align properly. I have tried this with several versions of Emacs (macports binaries 25.2.1 as well as savannah emacs compiled from scratch). But same issue. Here are a couple of screenshots:

![org-brain-align](https://cloud.githubusercontent.com/assets/1281353/26027418/9742d6f6-3805-11e7-8da0-a284ad598406.jpg)

![org-brain-align-2](https://cloud.githubusercontent.com/assets/1281353/26027464/3da5b16c-3806-11e7-869c-9c3bee4f08fc.jpg)

This one looks okay though:

![org-brain-align-3](https://cloud.githubusercontent.com/assets/1281353/26027468/4a03e898-3806-11e7-9003-f4f88cc1bb28.jpg)

and here is the `init.el` file I'm using:

    ;;;----- Startup --------------------------------;
    
    ;;; Add src directories to path
    (add-to-list 'load-path "~/.emacs.d/lisp")
    
    ;;; Add the melpa package archives
    (require 'package)
    (setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                             ("marmalade" . "https://marmalade-repo.org/packages/")
                             ("melpa" . "https://melpa.org/packages/")))
    
    ;;; Add packages to load-path
    (package-initialize)
    
    ;;;----- Org-mode -------------------------------;
    
    ;;; Add upgraded org-mode to load path
    (add-to-list 'load-path "~/.emacs.d/lisp/org-9.0.6/lisp")
    (add-to-list 'load-path "~/.emacs.d/lisp/org-9.0.6/contrib/lisp" t)
    
    ;;; Set default org-directory
    (setq org-directory "~/org")
    
    ;;; Activate org-mode
    (require 'org)
    
    ;;;----- Org-Brain ----------------------;
    
    (custom-set-variables
    ;; custom-set-variables was added by Custom.
    ;; If you edit it by hand, you could mess it up, so be careful.
    ;; Your init file should contain only one such instance.
    ;; If there is more than one, they won't work right.
    '(package-selected-packages (quote (org-brain))))
    (custom-set-faces
    ;; custom-set-faces was added by Custom.
    ;; If you edit it by hand, you could mess it up, so be careful.
    ;; Your init file should contain only one such instance.
    ;; If there is more than one, they won't work right.
    )

**Comment by Kungsgeten** [comment]
Hi!

The function that generates the diagram isn't very elegant, so there's probably a problem there somewhere. I'm not sure where though, its been working without issues for me on Linux and Windows. I'm using `goto-line` (which isn't recommended to use in elisp code) and also `picture` which I guess is a bit unorthodox to use in Elisp. The fault may lie there, or it may be a change in Emacs 25.2 causing the problems (I'm on 25.1).

Thanks for letting me know. It will probably be hard to fix it when I'm not experiencing it myself, but others may have similar problems and suggest fixes.

**Comment by Kungsgeten** [comment]
@adam52 Not sure if you're still using `org-brain`, but if so does it work better now?

**Comment by adam52** [comment]
I have not used it since, actually. Was waiting for any bugs to get worked out... Was this issue resolved?

**Comment by Kungsgeten** [comment]
Not sure. I haven't noticed any problems and neither have I heard anything
else about it. There has been some modifications to the "rendering", so
maybe it'll work now :)

**Comment by Kungsgeten** [comment]
Closing this, since I haven't heard it being misaligned for anyone else, and because it might have been fixed during the rewrite of the rendering. Feel free to open again if there's still problems.

**Comment by adam52** [comment]
I installed the latest org-brain and can confirm that this issue still exists. Here is my configuration.

### Packages

- Org-brain version 0.5
- GNU Emacs 26.1 (build 1, x86_64-apple-darwin18.0.0, Carbon Version 158 AppKit 1671) of 2018-10-01
- Org mode version 9.1.9 (9.1.9-elpaplus @ /Users/adamsneller/.emacs.d/elpa/org-plus-contrib-20180327/)

### Init file

    ;;; Add path to src directory
    (add-to-list 'load-path "~/.emacs.d/lisp")

    ;;; Set default org directory
    (setq default-directory "~/org/")

    ;;; Configure org-brain
    (require 'org-brain)
    (setq org-brain-path "~/org/brain")
    (setq org-id-track-globally t)
    (setq org-id-locations-file "~/.emacs.d/.org-id-locations")
    (setq org-brain-visualize-default-choices 'all)
    (setq org-brain-title-max-length 50)

### Results

![screen shot 2019-02-13 at 00 31 39](https://user-images.githubusercontent.com/1281353/52678115-661ec280-2f28-11e9-9ada-e6cadb73678a.jpg)

**Comment by adam52** [comment]
At this point, the enly time I notice any misalignment is when a node has two parents. Otherwise, it looks fine.
